[sdl]
fullscreen= false
output= overlay
fullresolution= 0x0
windowresolution= 640x480
autolock= false

[dosbox]
captures= .

[render]
aspect= false
scaler= normal2x

[cpu]
core= dynamic
cycles= max

[midi]
mpu401= intelligent
mididevice= win32
midiconfig=
