;======================================
; SCI Studio Template Game Project File
; By Brian Provinciano
;======================================

[Game]
ScummId=sci-fanmade
ExeProfile=DOSBox
Name=Trauma Response Simulator

[View]
n000=Ego
n800=Item - Test Object
n801=Player Portrait

[Pic]
n800=Title Screen
n001=rm001 Background
n000=Cave

[Script]
n000=Main
n973=Avoid
n974=Door
n975=AutoDoor
n976=InitRooms
n977=Dying
n978=DisposeLoad
n979=Controls
n980=DPath
n981=DCIcon
n982=Rev
n983=Wander
n984=Follow
n985=Timer
n986=Window
n987=Gauge
n988=Extra
n989=Sound
n990=SysWindow
n991=Jump
n992=Cycle
n993=FileIO
n994=Game
n995=Inv
n996=User
n997=MenuBar
n998=Feature
n999=Obj
n800=TitleScreen
n001=rm001
n002=rm002
n100=PrintChoices
n101=WorkEvents
n102=WorkEvents1
n103=WorkEvents2
n104=WorkEvents3
n105=WorkEvents4
n106=Mechanisms
n107=CaseFiles
n108=HomeEvents
n109=HomeEvents1
n110=HomeEvents2
n111=HomeEvents3
n112=HomeEvents4
n113=SocialEvents
n114=SocialEvents1
n115=SocialEvents2
n116=SocialEvents3
n117=SocialEvents4
n118=SelfEvents
n119=SelfEvents1
n120=SelfEvents2
n121=SelfEvents3
n122=SelfEvents4
n123=BodyEvents
n124=BodyEvents1
n125=BodyEvents2
n126=BodyEvents3
n127=BodyEvents4
n128=PublicEvents
n129=PublicEvents1
n130=PublicEvents2
n131=PublicEvents3
n132=PublicEvents4
n133=EndingContent1
n134=EndingContent2
n135=EndingContent3
n136=CaseFileAccess
n137=CaseFileTitles

[Cursor]
n997=Loading
n999=Arrow

[Font]
n000=Default Font
n001=Window Font
n004=Small Font
n009=Large Font
n999=Debug Font

[Vocab]
n000=Words
n999=Kernel Names
n998=Opcode Names
n997=Selector Names
n996=Class Table
n901=Suffixes
n995=Debug Info
n900=Black Box

[Sound]
n900=Score Sound
n001=Dummy
n002=Death Sound

[Patch]
n001=Roland MT-32
n002=IBM Music Feature/Yamaha FM-01
n003=Adlib  
n004=Yamaha FM-01 
n007=Casio CSM-1 
n101=CMS/Game Blaster 

