/******************************************************************************
 T.R.S. → SCI0 port
 ******************************************************************************
 CaseFileDescriptionsSurvival.sc
 GENERATED FILE — do not hand-edit. Produced by
 tools/gen-casefile-descriptions.js from js/content-endings.js and
 js/content-mechanisms.js.

 Survival ending descriptions for the Case Files viewer's "View" detail
 screen, flat indices 0-71 (game.sh's index scheme).
 Load/DisposeScript-scoped -- only needed while this category's
 screen is open.
 ******************************************************************************/
(include "sci.sh")
(include "game.sh")
/******************************************************************************/
(script CASEFILEDESCRIPTIONS_SURVIVAL_SCRIPT)
/******************************************************************************/
(procedure public (CaseFileDescriptionSurvival index)
	(switch(index)
		(case 0 return("You didn't explode. You just got very, very good at ticking."))
		(case 1 return("You didn't self-destruct, yet. Today just isn't over anywhere else, either."))
		(case 2 return("Something in you is very close to the surface. You made it to the deadline before it did."))
		(case 3 return("You survived by holding something in the whole way through. Your shoulders will remember this tomorrow."))
		(case 4 return("Not boiling over. Not cooled down either. Just holding at a temperature (that isn't sustainable)."))
		(case 5 return("You made it through; white-knuckled. Nobody else could tell. Your jaw could."))
		(case 6 return("You crossed the finish line still overheating. The engine didn't seize. It was a close one, though."))
		(case 7 return("Whatever's in there is still in there."))
		(case 8 return("Nobody has seen the real you in years, including you."))
		(case 9 return("You hit every mark, said every right thing, and couldn't tell anyone what it cost until just now."))
		(case 10 return("You've played the part of yourself so long the understudy might genuinely be better at it by now."))
		(case 11 return("The performance was seamless. Nobody asks what happens after the curtain, including you."))
		(case 12 return("You do a very good impression of someone who's fine. Most days, even you almost believe it."))
		(case 13 return("Everyone clapped. You bowed. Somewhere backstage, something's been waiting a long time for its cue."))
		(case 14 return("It fits so well now you forget you put it on this morning. Or any morning."))
		(case 15 return("Smooth all the way down, as far as anyone can tell, including the part of you that used to check."))
		(case 16 return("You stopped hiding. It cost you more than you expected, but you kept yourself."))
		(case 17 return("People saw the real thing, unedited. Some of them left. You're still here, which is the point."))
		(case 18 return("You ran out of energy for the act partway through and just stopped. Turns out that was allowed."))
		(case 19 return("It isn't pretty. It isn't curated. It's yours, all the way through, for the first time in a while."))
		(case 20 return("You let people see the parts you used to manage. A few flinched. You didn't take it back."))
		(case 21 return("Being yourself had a price today. You paid it and you're still standing in the same shoes."))
		(case 22 return("Nothing about today was smooth. All of it was real, which turned out to matter more."))
		(case 23 return("You stopped insulating yourself from being seen. It sparked a little. You're still conducting."))
		(case 24 return("You stopped filtering. Everything's a little too loud and a little too close to the surface right now."))
		(case 25 return("The mask came off somewhere along the way and you never found a good moment to put it back on."))
		(case 26 return("Whatever usually buffers you from the world just wasn't there today. You felt everything at full volume."))
		(case 27 return("People got the real reaction, in real time, with none of the usual smoothing. It was a lot. For everyone."))
		(case 28 return("You spent the day one comment away from visibly reacting to everything. Some days are just like that."))
		(case 29 return("The usual layer between you and the day just wasn't there. You made it through anyway, a little rawer for it."))
		(case 30 return("You didn't cover anything up today. It wasn't strategic. It just happened, and here you still are."))
		(case 31 return("There was no version of today where you could smooth this over. So you didn't. That's new, for you."))
		(case 32 return("You looked fine all day. You have no real idea what was actually fueling that."))
		(case 33 return("From the outside, a completely normal day. On the inside, mostly static."))
		(case 34 return("You showed up, said the right things, looked put-together. Nothing underneath was doing the same."))
		(case 35 return("Everything worked. Nothing felt like anything. Both of those are true at once."))
		(case 36 return("You got through today on muscle memory and social competence. The rest of you clocked out hours ago."))
		(case 37 return("You were pleasant to everyone today. You couldn't say which of your own feelings, if any, showed up."))
		(case 38 return("Nothing cracked today. Nothing underneath the surface was really there to crack, either."))
		(case 39 return("You kept the shape of a normal day. Whatever's supposed to fill that shape took the day off."))
		(case 40 return("Nothing is fixed. Nothing is on fire. This might be what okay feels like."))
		(case 41 return("Not great, not terrible. You're starting to suspect that's just what most days actually are."))
		(case 42 return("Everything's balanced today. You know better than to assume that's permanent. You'll take it anyway."))
		(case 43 return("Nothing demanded a reaction today. That's rarer than it should be, and you noticed it."))
		(case 44 return("Not fixed. Not falling apart. Just steady, in a way that felt almost unfamiliar by the end of it."))
		(case 45 return("Not thriving, not failing. Somewhere in the wide, unglamorous middle most of life actually happens in."))
		(case 46 return("Nothing today asked more of you than you had. That in itself felt like a small, quiet win."))
		(case 47 return("The boat didn't rock much today. You're starting to remember what that's supposed to feel like."))
		(case 48 return("Not surviving. Not performing. Just, for once, actually okay. You can tell the difference from the inside."))
		(case 49 return("This isn't the version of fine you perform for other people. This is the actual, unperformed version."))
		(case 50 return("Good, without a footnote explaining why it doesn't count. You keep waiting for the footnote. It doesn't come."))
		(case 51 return("Nobody's throwing you a parade for this, and it doesn't need one. You're just genuinely doing well, today."))
		(case 52 return("You didn't have to build this feeling. It was just there today, the way it's supposed to be sometimes."))
		(case 53 return("Nothing underneath you feels like it's about to give way. You're still getting used to that."))
		(case 54 return("This good day wasn't a mask. You checked. Twice. It held up both times."))
		(case 55 return("Same shape as a good day you'd fake for someone else's benefit. The difference is nobody had to be convinced, including you."))
		(case 56 return("You're carrying more than you'd like to admit, and carrying it fine, for now."))
		(case 57 return("Nothing broke today. A few things bent. You're still counting that as a win."))
		(case 58 return("Not thriving. Not drowning. Actively, deliberately managing, which is its own quiet kind of work."))
		(case 59 return("Something in you is pulled tight and hasn't snapped. You've gotten used to the tightness."))
		(case 60 return("The weight's real. You're still standing under it. That's not nothing."))
		(case 61 return("Not boiling. Not cold. Just holding at a low, steady heat that takes real effort to maintain."))
		(case 62 return("This isn't a crisis. It's just a lot, held at a pace you can actually keep up."))
		(case 63 return("You're wound tighter than you'd like. You're also, somehow, still getting things done."))
		(case 64 return("You made it to tomorrow. Good job."))
		(case 65 return("That's it. Some days that's the entire accomplishment."))
		(case 66 return("Nothing about today fits a neater category than this. You got through it. That counts."))
		(case 67 return("No dramatic collapse, no dramatic triumph. Just a day, ending, with you still in it."))
		(case 68 return("Not the best day. Not the worst. A perfectly forgettable, perfectly fine day, and those matter too."))
		(case 69 return("This isn't the ending with a moral. It's just the one where you made it to the last turn."))
		(case 70 return("No collapse. No breakthrough. Just a day that happened, the way most of them do."))
		(case 71 return("Most days end like this: quietly, without a headline. This was one of those."))
	)
	return("")
)
/******************************************************************************/
