/******************************************************************************
 T.R.S. → SCI0 port
 ******************************************************************************
 casefiletitles.sc
 Split out of casefileaccess.sc after a real heap-exhaustion bug (see
 SESSION_HANDOFF.md): Main.sc calls GetCaseFile() directly at boot (for
 the gNgPlusUnlocked mirror sync), which made the whole of
 casefileaccess.sc permanently resident from the start of the game --
 including this 107-case CaseFileTitle() switch, which is ONLY ever
 actually needed by ShowCaseFiles() (casefiles.sc), a screen most turns
 never open. Kept as its own script specifically so ShowCaseFiles() can
 Load(rsSCRIPT CASEFILETITLES_SCRIPT)/DisposeScript(...) it around just
 that one use, instead of paying its ~4.9KB permanently for the entire
 session -- same Load/DisposeScript idiom used throughout this codebase
 for anything that shouldn't stay permanently resident.
 ******************************************************************************/
(include "sci.sh")
(include "game.sh")
/******************************************************************************/
(script CASEFILETITLES_SCRIPT)
/******************************************************************************/
/******************************************************************************/
(procedure public (CaseFileTitle index)
	// Indices 0-101: one title per ending variant (see game.sh's full
	// index scheme and tools/gen-endings.js), same order as
	// endingcontent1-3.sc's PrintSurvivalEnding0..8/PrintFailureEnding0..2
	// switches -- duplicated here rather than shared, there's no clean way
	// to share a string constant across scripts in this language, and
	// each is short. Indices 102-106: the 5 coping-mechanism titles
	// (unchanged text from the original 12-16 numbering, also duplicated
	// against mechanisms.sc's own "COPING MECHANISM ACQUIRED" messages).
	(switch(index)
		(case 0 return("The Powder Keg"))
		(case 1 return("Holding Pattern"))
		(case 2 return("Pressure Cooker"))
		(case 3 return("The Held Breath"))
		(case 4 return("Simmering"))
		(case 5 return("The Clenched Jaw Ending"))
		(case 6 return("Running Hot"))
		(case 7 return("Barely Contained"))
		(case 8 return("The Performer"))
		(case 9 return("Note-Perfect"))
		(case 10 return("The Understudy"))
		(case 11 return("Flawless Execution"))
		(case 12 return("The Convincing Copy"))
		(case 13 return("Standing Ovation"))
		(case 14 return("The Mask That Fits"))
		(case 15 return("All Surface, No Depth Charge"))
		(case 16 return("Radically Undone"))
		(case 17 return("The Unvarnished Version"))
		(case 18 return("Nothing Left to Perform"))
		(case 19 return("The Honest Wreckage"))
		(case 20 return("Seen and Not Sorry"))
		(case 21 return("The Costly Truth"))
		(case 22 return("Unpolished"))
		(case 23 return("The Exposed Wire"))
		(case 24 return("Raw Nerve"))
		(case 25 return("Nothing Between You And It"))
		(case 26 return("Exposed Wiring"))
		(case 27 return("The Unfiltered Version"))
		(case 28 return("Too Close To The Surface"))
		(case 29 return("Skinless"))
		(case 30 return("The Open Wound Approach"))
		(case 31 return("Nowhere to Hide It"))
		(case 32 return("Coasting on Empty"))
		(case 33 return("Running on Fumes and Good Posture"))
		(case 34 return("Presentable"))
		(case 35 return("The Functional Hollow"))
		(case 36 return("Autopilot, Well-Dressed"))
		(case 37 return("Numb But Nice About It"))
		(case 38 return("The Smooth Surface"))
		(case 39 return("Holding the Shape"))
		(case 40 return("Fragile Equilibrium"))
		(case 41 return("The Uneasy Middle"))
		(case 42 return("Level, For Now"))
		(case 43 return("A Quiet Enough Day"))
		(case 44 return("Holding Steady"))
		(case 45 return("The In-Between"))
		(case 46 return("Manageable"))
		(case 47 return("Even Keel"))
		(case 48 return("Actually Okay"))
		(case 49 return("The Real Thing"))
		(case 50 return("No Asterisk"))
		(case 51 return("Quietly Thriving"))
		(case 52 return("The Unforced Smile"))
		(case 53 return("Solid Ground"))
		(case 54 return("Earned, Not Performed"))
		(case 55 return("The Genuine Article"))
		(case 56 return("The Long Fuse"))
		(case 57 return("Holding It Together, Mostly"))
		(case 58 return("Managing"))
		(case 59 return("The Working Tension"))
		(case 60 return("Under Pressure, Upright"))
		(case 61 return("Simmer Setting"))
		(case 62 return("The Sustainable Strain"))
		(case 63 return("Tightly Wound, Still Functional"))
		(case 64 return("Functional Enough"))
		(case 65 return("You're Still Here"))
		(case 66 return("Day Survived"))
		(case 67 return("The Unremarkable Ending"))
		(case 68 return("Adequate"))
		(case 69 return("Good Enough, For Now"))
		(case 70 return("Nothing To Report"))
		(case 71 return("The Ordinary Ending"))
		(case 72 return("Panic Attack"))
		(case 73 return("Tectonic Reset"))
		(case 74 return("The Blowup"))
		(case 75 return("System Overpressure"))
		(case 76 return("Full Meltdown"))
		(case 77 return("The Snap"))
		(case 78 return("Delayed Detonation"))
		(case 79 return("Public Unraveling"))
		(case 80 return("The Overflow"))
		(case 81 return("Structural Failure"))
		(case 82 return("Social Exile"))
		(case 83 return("The Unmasking"))
		(case 84 return("Honesty, Uninvited"))
		(case 85 return("No Filter Left"))
		(case 86 return("The Reveal"))
		(case 87 return("Radical Candor (Involuntary)"))
		(case 88 return("Exiled"))
		(case 89 return("The Real You, Unscheduled"))
		(case 90 return("Social Combustion"))
		(case 91 return("Unfiltered"))
		(case 92 return("Total Disassociation"))
		(case 93 return("Autopilot Engaged"))
		(case 94 return("The Hollow"))
		(case 95 return("Nobody Home"))
		(case 96 return("Flatline"))
		(case 97 return("Muscle Memory Only"))
		(case 98 return("The Static"))
		(case 99 return("Checked Out"))
		(case 100 return("The Long Blink"))
		(case 101 return("Running on Empty"))
		(case 102 return("The Approval Loop"))
		(case 103 return("The Exit Strategy"))
		(case 104 return("Hair-Trigger"))
		(case 105 return("The Void"))
		(case 106 return("Earned Security"))
	)
	return("")
)
