/******************************************************************************
 T.R.S. → SCI0 port
 ******************************************************************************
 casefiles.sc
 Cross-run "Case Files" persistence (matches the original browser game's
 Case Files feature, README.md: "a persistent, cross-run record of every
 ending and coping mechanism you've ever actually seen"). Full ending-
 variant port (see SESSION_HANDOFF.md): tracks discovery per VARIANT now
 (all 9 survival pools x 8 variants + 3 failure pools x 10 variants = 102
 total), matching the original's actual "collect every ending" mechanic --
 not just per ending CONDITION like this port's earlier one-variant-per-
 pool scope cut did. Still a real external file, following the same
 QFG-style pattern documented in docs/SCI0-research-findings.md: plain
 ASCII, one value per line, FOpen/FGets/FPuts/FClose via the template's
 fileio.sc.

 gCF0..gCF107 (declared in Main.sc, CASEFILE_COUNT = 108 of them) hold the
 in-memory discovery flags for this session -- individual scalar globals,
 not an array (see SESSION_HANDOFF.md for why). GetCaseFile/SetCaseFile
 (casefileaccess.sc, split out separately -- see its own header) are the
 array-like accessors everything else (including MarkCaseFile below)
 actually uses; nothing outside casefileaccess.sc needs to know they're
 really 108 separate globals. LoadCaseFiles()/SaveCaseFiles() sync all 108 with
 TRSCASE.DAT (a bare filename -- resolves relative to the game's own
 directory, same as the stock SRDialog code's own file access). Slot 107
 (CASEFILE_NGPLUS) is the unrelated Extended Therapy unlock flag, not a
 real case file -- riding on this file/array purely because it's the one
 proven persistence mechanism in this codebase (see game.sh); the viewer
 stays scoped to VIEWABLE_CASEFILE_COUNT (107) so it doesn't show up as a
 bogus 108th entry. See game.sh for the full index scheme (0-71 survival
 variants, 72-101 failure variants, 102-106 mechanisms, 107 NG+) and
 tools/gen-endings.js for how the 102 ending-variant slots' content
 actually gets generated.

 ShowCaseFiles() is a category menu (Survival Endings / Failure Endings /
 Coping Mechanisms, matching the original browser game's own
 js/codex.js grouping) that opens ShowCaseFileCategory() scoped to just
 that range -- a DSelector list, same as this viewer's original
 browse-only v1, plus a "View" button that shows the full title+
 description (or a "sealed" placeholder) for whichever entry is
 highlighted. Descriptions come from CaseFileDescription()
 (CaseFileDescriptions.sc, generated by
 tools/gen-casefile-descriptions.js -- same Load/DisposeScript-scoped,
 only-needed-by-this-screen idiom as CaseFileTitle()/CaseFileTitles.sc).
 ******************************************************************************/
(include "sci.sh")
(include "game.sh")
/******************************************************************************/
(script CASEFILES_SCRIPT)
/******************************************************************************/
(use "main")
(use "controls")
(use "casefileaccess")
(use "casefiletitles")
(use "casefiledescriptions")
/******************************************************************************/
// Script-level local, not a per-call procedure local -- see
// ShowCaseFiles() below and SESSION_HANDOFF.md. Same declaration idiom
// User.sc's own inputStr[51] already uses for a script-local array (a
// (local ...) block right after the (use ...) list, not inside any one
// procedure/method).
(local
	buf[3424]
)
/******************************************************************************/
(procedure public (LoadCaseFiles)
	(var hFile, i, lineBuf[6])
	// Deliberately fOPENCREATE here, not fOPENFAIL -- see game.sh/
	// SESSION_HANDOFF.md: SCI0's fOPENFAIL/fOPENCREATE numeric values
	// are swapped from what their names suggest (confirmed via SCI
	// Companion's own bundled FOpen.html kernel docs and sci.sh's
	// #ifdef SCI_0 block) -- fOPENCREATE is the one that actually
	// means "open existing, abort/fail if not possible", which is
	// the safe read-only semantics this procedure needs. Using
	// fOPENFAIL here (as this procedure did for this entire project
	// up to this fix) actually invokes "open or create" behavior,
	// which turns out to truncate/reset the file's content before
	// this procedure ever gets to read it -- the real root cause of
	// the New Game+ debugging saga above: every load was silently
	// wiping TRSCASE.DAT immediately before trying to read it back.
	= hFile FOpen("TRSCASE.DAT" fOPENCREATE)
	// Checking truthiness rather than == -1 specifically, matching
	// the stock fileio.sc File class's own defensive pattern -- NULL
	// is 0 in this dialect (confirmed via sci.sh), and it's not
	// certain a failed FOpen always returns -1 rather than NULL/0
	// specifically.
	(if(not hFile)
		return
	)
	// Load/DisposeScript wrapped around just the loop that actually needs
	// SetCaseFile -- CaseFileAccess.sc used to be permanently resident
	// (implicitly, since nothing ever disposed it), a real contributor to
	// a heap-exhaustion bug during ordinary per-turn play; see
	// SESSION_HANDOFF.md. Placed after the early-return above so a
	// missing save file (nothing to load) never touches it at all.
	Load(rsSCRIPT CASEFILEACCESS_SCRIPT)
	(for (= i 0) (< i CASEFILE_COUNT) (++i)
		FGets(@lineBuf 6 hFile)
		SetCaseFile(i ReadNumber(@lineBuf))
	)
	DisposeScript(CASEFILEACCESS_SCRIPT)
	FClose(hFile)
)
/******************************************************************************/
(procedure public (SaveCaseFiles)
	// Deliberately does NOT Load/DisposeScript CaseFileAccess.sc itself --
	// this is only ever called from MarkCaseFile below, which already
	// wraps its own call to this with one Load/Dispose pair covering
	// both. A second, nested pair here would be redundant at best; if
	// this ever gets a second caller, that caller needs to do its own
	// wrapping (or this procedure should grow one) rather than assuming
	// it's free.
	(var hFile, i, lineBuf[6])
	= hFile FOpen("TRSCASE.DAT" fCREATE)
	(if(== hFile -1)
		return
	)
	(for (= i 0) (< i CASEFILE_COUNT) (++i)
		Format(@lineBuf "%d\n" GetCaseFile(i))
		FPuts(hFile @lineBuf)
	)
	FClose(hFile)
)
/******************************************************************************/
(procedure public (MarkCaseFile index)
	// Flips this case file permanently and persists it right away if this
	// is the first time it's ever been seen. Returns TRUE exactly when
	// that happened, so callers can decide whether to announce it -- this
	// procedure itself never prints anything.
	// Load/DisposeScript wrapped -- covers this procedure's own direct
	// GetCaseFile/SetCaseFile calls AND the nested SaveCaseFiles() call
	// (which also uses GetCaseFile internally) with a single pair, rather
	// than double-wrapping SaveCaseFiles separately -- SaveCaseFiles is
	// only ever called from here, so this is its one true entry point.
	Load(rsSCRIPT CASEFILEACCESS_SCRIPT)
	(if(not GetCaseFile(index))
		SetCaseFile(index 1)
		SaveCaseFiles()
		DisposeScript(CASEFILEACCESS_SCRIPT)
		return(TRUE)
	)
	DisposeScript(CASEFILEACCESS_SCRIPT)
	return(FALSE)
)
/******************************************************************************/
(procedure public (UnlockNgPlus)
	// Extended Therapy / New Game+ unlock flag (see game.sh's Extended
	// Therapy block for why this rides on gCaseFiles/TRSCASE.DAT as slot
	// CASEFILE_NGPLUS instead of its own file). Matches js/engine.js's
	// unlockNgPlus() -- called from rm002.sc's printSurvivalEnding() exactly
	// where the original calls it from checkGameEnd(). MarkCaseFile already
	// gives the right semantics here: sets the slot and persists
	// immediately, but only actually writes to disk the first time (a
	// harmless, strictly cheaper divergence from the original's
	// unconditional-every-survival localStorage write). gNgPlusUnlocked
	// (the in-memory mirror everything else reads) still gets set every
	// call regardless, matching the original's idempotent-either-way call
	// site.
	MarkCaseFile(CASEFILE_NGPLUS)
	= gNgPlusUnlocked TRUE
)
/******************************************************************************/
(procedure public (ShowCaseFiles)
	// Category menu -- reachable any time via the "Case Files" menu item
	// (menubar.sc), including from the ending room, since nothing hides
	// the menu bar there. Hand-rolled vertically-stacked DButtons (same
	// Dialog/DButton/DText primitives and nsTop-clamp-after-center()
	// defensive pattern ShowCaseFileCategory() and PrintChoices both use)
	// rather than calling PrintChoices() itself -- PrintChoices (use
	// "mechanisms"), and mechanisms.sc (use "casefiles") right back, so
	// calling it from here would open a brand-new 3-hop (use ...) cycle
	// this codebase has never actually compiled before (CaseFiles ->
	// PrintChoices -> Mechanisms -> CaseFiles). The 2-hop CaseFiles.sc/
	// Main.sc cycle already needed a manual bootstrap compile once (see
	// SESSION_HANDOFF.md); not worth gambling a 3-hop one compiles clean
	// on the first try when a few extra lines avoids it entirely.
	//
	// Button *values* here are 1/2/3, deliberately never 0 -- Dialog:doit()
	// returns plain 0/FALSE on Escape (not a button pointer), so 0 stays
	// an unambiguous "cancelled, do nothing" sentinel distinct from any
	// real choice.
	(var hDialog, hDText, hButtons[3], i, curY, hResult, choice)
	= hDialog (Dialog:new())
	(send hDialog:
		window(gTheWindow)
		name("CaseFilesD")
		text("Case Files")
	)
	= hDText (DText:new())
	(send hDText:
		text("Every ending and coping mechanism you've ever discovered, across every run. Choose a category to browse:")
		font(gDefaultFont)
		moveTo(4 4)
		setSize(290)
	)
	(send hDialog:add(hDText))
	= curY (+ (send hDText:nsBottom) 6)

	= hButtons[0] (DButton:new())
	(send hButtons[0]:
		text("Survival Endings")
		value(1)
		font(SMALL_FONT)
		setSize()
		moveTo(4 curY)
	)
	(send hDialog:add(hButtons[0]))
	= curY (+ (send hButtons[0]:nsBottom) 3)

	= hButtons[1] (DButton:new())
	(send hButtons[1]:
		text("Failure Endings")
		value(2)
		font(SMALL_FONT)
		setSize()
		moveTo(4 curY)
	)
	(send hDialog:add(hButtons[1]))
	= curY (+ (send hButtons[1]:nsBottom) 3)

	= hButtons[2] (DButton:new())
	(send hButtons[2]:
		text("Coping Mechanisms")
		value(3)
		font(SMALL_FONT)
		setSize()
		moveTo(4 curY)
	)
	(send hDialog:add(hButtons[2]))

	(send hDialog:
		setSize()
		center()
	)
	(if(< (send hDialog:nsTop) 2)
		// Same defensive clamp as PrintChoices -- see SESSION_HANDOFF.md.
		(send hDialog:moveTo( (send hDialog:nsLeft) 2 ))
	)
	(send hDialog:open(nwTITLE -1))
	= hResult (send hDialog:doit(NULL))
	// Same "match the returned control pointer against each button,
	// extract its :value" pattern PrintChoices itself uses -- a flat
	// for-loop with an early break, not a chained if/else (see
	// SESSION_HANDOFF.md: no confirmed precedent for 3+-branch chaining
	// in this codebase).
	= choice 0
	(for (= i 0) (< i 3) (++i)
		(if(== hResult hButtons[i])
			= choice (send hButtons[i]:value)
			break
		)
	)
	(send hDialog:dispose())

	(if(== choice 1)
		ShowCaseFileCategory(CASEFILE_SURVIVAL_BASE CASEFILE_SURVIVAL_COUNT "Survival Endings")
	)
	(if(== choice 2)
		ShowCaseFileCategory(CASEFILE_FAILURE_BASE CASEFILE_FAILURE_COUNT "Failure Endings")
	)
	(if(== choice 3)
		ShowCaseFileCategory(CASEFILE_MECH_BASE CASEFILE_MECH_COUNT "Coping Mechanisms")
	)
)
/******************************************************************************/
(procedure public (ShowCaseFileCategory baseIndex count catTitle)
	// public, not private -- every other procedure in this codebase is
	// declared public (grepped for a private-procedure precedent, found
	// none); matching that rather than risking an untested pattern for no
	// real benefit, since nothing outside this file needs to call it
	// anyway.
	// The actual scrolling list for one category -- same DSelector-based
	// approach as this viewer's original single flat list (see
	// SESSION_HANDOFF.md: chosen specifically to avoid the dialog-height
	// overflow failure mode that bit this project twice for tall
	// multi-item dialogs), just windowed to [baseIndex, baseIndex+count)
	// instead of the full 107. Adds a "View" button next to the selector:
	// highlighting an entry (arrow keys/Page Up-Down/mouse, same as
	// before) and clicking View shows that entry's title+description if
	// discovered, or a sealed placeholder if not.
	(var hDialog, hSelector, hDText, hViewBtn, hCloseBtn, i, curY, hResult,
		localIndex, flatIndex, discovered)
	// buf is the same script-level local ShowCaseFiles() used to use
	// directly (see its own comment above, now moved here) -- still
	// sized for the largest category (Survival, 72 * 32 = 2304 bytes),
	// comfortably within its declared 3424-byte capacity, left untouched
	// at that size rather than resized: it's already confirmed working at
	// 3424 (a real runtime crash, not just a compile error, when this was
	// briefly tried as a per-call procedure local instead of a
	// script-level one), and resizing it isn't needed for this feature.
	(for (= i 0) (< i (* count 32)) (++i)
		= buf[i] 0
	)
	Load(rsSCRIPT CASEFILETITLES_SCRIPT)
	Load(rsSCRIPT CASEFILEACCESS_SCRIPT)
	(for (= i 0) (< i count) (++i)
		(if(GetCaseFile(+ baseIndex i))
			Format((+ @buf (* i 32)) "%d. %s" (+ i 1) CaseFileTitle(+ baseIndex i))
		)(else
			Format((+ @buf (* i 32)) "%d. ??? (sealed)" (+ i 1))
		)
	)
	DisposeScript(CASEFILEACCESS_SCRIPT)
	DisposeScript(CASEFILETITLES_SCRIPT)

	= hDialog (Dialog:new())
	(send hDialog:
		window(gTheWindow)
		name("CaseFilesD")
		text(catTitle)
	)
	= hDText (DText:new())
	(send hDText:
		text("Select an entry, then View to read it.")
		font(gDefaultFont)
		moveTo(4 4)
		setSize(290)
	)
	(send hDialog:add(hDText))
	= curY (+ (send hDText:nsBottom) 6)

	= hSelector (DSelector:new())
	(send hSelector:
		text(@buf)
		x(32)
		// 8 rows, not the flat list's original 10 -- this screen also
		// needs room below the selector for the View/Close buttons, and
		// still comfortably fits every category (including the 72-entry
		// Survival list, which just scrolls) within the same ~190px
		// dialog-height budget PrintChoices/the original list already
		// have to respect (see SESSION_HANDOFF.md's tall-dialog findings).
		y(8)
		font(SMALL_FONT)
		// state bit 1 (TRUE), not bit 2 -- see SESSION_HANDOFF.md's own
		// account of the auto-close bug this exact distinction fixed the
		// first time this viewer was built. Still correct here: the
		// selector should only ever change focus/highlight, never end the
		// dialog's modal loop by itself.
		state(1)
		moveTo(4 curY)
		setSize()
	)
	(send hDialog:add(hSelector))
	= curY (+ (send hSelector:nsBottom) 4)

	= hViewBtn (DButton:new())
	(send hViewBtn:
		text("View")
		value(1)
		font(SMALL_FONT)
		setSize()
		moveTo(4 curY)
	)
	(send hDialog:add(hViewBtn))

	= hCloseBtn (DButton:new())
	(send hCloseBtn:
		text("Close")
		value(2)
		font(SMALL_FONT)
		setSize()
		moveTo( (+ (send hViewBtn:nsRight) 6) curY)
	)
	(send hDialog:add(hCloseBtn))

	(send hDialog:
		setSize()
		center()
	)
	(if(< (send hDialog:nsTop) 2)
		(send hDialog:moveTo( (send hDialog:nsLeft) 2 ))
	)
	(send hDialog:open(nwTITLE -1))

	// Deliberately one Dialog:open() for the whole loop, not re-opened per
	// View click -- doit(hSelector) is just called again each time,
	// keeping the same hSelector instance (and so its cursor/mark/lsTop
	// scroll position) alive across multiple View clicks. Escape or Close
	// both fall out here identically: Dialog:doit() returns plain 0 for
	// Escape, and hCloseBtn's own returned pointer never equals hViewBtn
	// either way.
	(while(1)
		= hResult (send hDialog:doit(hSelector))
		(if(<> hResult hViewBtn)
			break
		)
		// Selected row's buffer position IS its index within this
		// category -- same 32-byte-stride arithmetic SRDialog's own
		// selectorI:indexOf(selectorI:cursor) pattern is built on
		// (docs/SCI0-research-findings.md / stock syswindow.sc), just
		// computed directly by pointer math instead of a string-compare
		// scan, since every row here is already known to be unique
		// (numbered).
		= localIndex (/ (- (send hSelector:cursor) @buf) 32)
		= flatIndex (+ baseIndex localIndex)

		Load(rsSCRIPT CASEFILEACCESS_SCRIPT)
		= discovered GetCaseFile(flatIndex)
		DisposeScript(CASEFILEACCESS_SCRIPT)

		(if(discovered)
			Load(rsSCRIPT CASEFILETITLES_SCRIPT)
			Load(rsSCRIPT CASEFILEDESCRIPTIONS_SCRIPT)
			Print(CaseFileDescription(flatIndex) #title CaseFileTitle(flatIndex))
			DisposeScript(CASEFILEDESCRIPTIONS_SCRIPT)
			DisposeScript(CASEFILETITLES_SCRIPT)
		)(else
			Print("Sealed. Not yet discovered." #title "???")
		)
	)
	(send hDialog:dispose())
)
/******************************************************************************/
