/******************************************************************************
 T.R.S. → SCI0 port
 ******************************************************************************
 endingcontent1.sc
 GENERATED FILE — do not hand-edit. Produced by tools/gen-endings.js from
 js/content-endings.js. Re-run that script after editing the source data.

 Survival ending pools 0-4 (5 pools x 8 variants = 40), matching CONTENT_ENDINGS in js/content-endings.js. Flat Case Files indices 0-39 -- see game.sh.
 ******************************************************************************/
(include "sci.sh")
(include "game.sh")
/******************************************************************************/
(script ENDINGCONTENT1_SCRIPT)
/******************************************************************************/
(use "main")
(use "controls")
(use "casefiles")
/******************************************************************************/
(procedure public (PrintSurvivalEnding0)
	(var variantIndex)
	= variantIndex Random(0 7)
	(switch(variantIndex)
		(case 0
			Print("You didn't explode. You just got very, very good at ticking." #title "The Powder Keg")
			(if(MarkCaseFile(0))
				Print("Case Files: The Powder Keg, filed." #title "New Case File")
			)
		)
		(case 1
			Print("You didn't self-destruct, yet. Today just isn't over anywhere else, either." #title "Holding Pattern")
			(if(MarkCaseFile(1))
				Print("Case Files: Holding Pattern, filed." #title "New Case File")
			)
		)
		(case 2
			Print("Something in you is very close to the surface. You made it to the deadline before it did." #title "Pressure Cooker")
			(if(MarkCaseFile(2))
				Print("Case Files: Pressure Cooker, filed." #title "New Case File")
			)
		)
		(case 3
			Print("You survived by holding something in the whole way through. Your shoulders will remember this tomorrow." #title "The Held Breath")
			(if(MarkCaseFile(3))
				Print("Case Files: The Held Breath, filed." #title "New Case File")
			)
		)
		(case 4
			Print("Not boiling over. Not cooled down either. Just holding at a temperature (that isn't sustainable)." #title "Simmering")
			(if(MarkCaseFile(4))
				Print("Case Files: Simmering, filed." #title "New Case File")
			)
		)
		(case 5
			Print("You made it through; white-knuckled. Nobody else could tell. Your jaw could." #title "The Clenched Jaw Ending")
			(if(MarkCaseFile(5))
				Print("Case Files: The Clenched Jaw Ending, filed." #title "New Case File")
			)
		)
		(case 6
			Print("You crossed the finish line still overheating. The engine didn't seize. It was a close one, though." #title "Running Hot")
			(if(MarkCaseFile(6))
				Print("Case Files: Running Hot, filed." #title "New Case File")
			)
		)
		(case 7
			Print("Whatever's in there is still in there." #title "Barely Contained")
			(if(MarkCaseFile(7))
				Print("Case Files: Barely Contained, filed." #title "New Case File")
			)
		)
	)
)
/******************************************************************************/
(procedure public (PrintSurvivalEnding1)
	(var variantIndex)
	= variantIndex Random(0 7)
	(switch(variantIndex)
		(case 0
			Print("Nobody has seen the real you in years, including you." #title "The Performer")
			(if(MarkCaseFile(8))
				Print("Case Files: The Performer, filed." #title "New Case File")
			)
		)
		(case 1
			Print("You hit every mark, said every right thing, and couldn't tell anyone what it cost until just now." #title "Note-Perfect")
			(if(MarkCaseFile(9))
				Print("Case Files: Note-Perfect, filed." #title "New Case File")
			)
		)
		(case 2
			Print("You've played the part of yourself so long the understudy might genuinely be better at it by now." #title "The Understudy")
			(if(MarkCaseFile(10))
				Print("Case Files: The Understudy, filed." #title "New Case File")
			)
		)
		(case 3
			Print("The performance was seamless. Nobody asks what happens after the curtain, including you." #title "Flawless Execution")
			(if(MarkCaseFile(11))
				Print("Case Files: Flawless Execution, filed." #title "New Case File")
			)
		)
		(case 4
			Print("You do a very good impression of someone who's fine. Most days, even you almost believe it." #title "The Convincing Copy")
			(if(MarkCaseFile(12))
				Print("Case Files: The Convincing Copy, filed." #title "New Case File")
			)
		)
		(case 5
			Print("Everyone clapped. You bowed. Somewhere backstage, something's been waiting a long time for its cue." #title "Standing Ovation")
			(if(MarkCaseFile(13))
				Print("Case Files: Standing Ovation, filed." #title "New Case File")
			)
		)
		(case 6
			Print("It fits so well now you forget you put it on this morning. Or any morning." #title "The Mask That Fits")
			(if(MarkCaseFile(14))
				Print("Case Files: The Mask That Fits, filed." #title "New Case File")
			)
		)
		(case 7
			Print("Smooth all the way down, as far as anyone can tell, including the part of you that used to check." #title "All Surface, No Depth Charge")
			(if(MarkCaseFile(15))
				Print("Case Files: All Surface, No Depth Charge, filed." #title "New Case File")
			)
		)
	)
)
/******************************************************************************/
(procedure public (PrintSurvivalEnding2)
	(var variantIndex)
	= variantIndex Random(0 7)
	(switch(variantIndex)
		(case 0
			Print("You stopped hiding. It cost you more than you expected, but you kept yourself." #title "Radically Undone")
			(if(MarkCaseFile(16))
				Print("Case Files: Radically Undone, filed." #title "New Case File")
			)
		)
		(case 1
			Print("People saw the real thing, unedited. Some of them left. You're still here, which is the point." #title "The Unvarnished Version")
			(if(MarkCaseFile(17))
				Print("Case Files: The Unvarnished Version, filed." #title "New Case File")
			)
		)
		(case 2
			Print("You ran out of energy for the act partway through and just stopped. Turns out that was allowed." #title "Nothing Left to Perform")
			(if(MarkCaseFile(18))
				Print("Case Files: Nothing Left to Perform, filed." #title "New Case File")
			)
		)
		(case 3
			Print("It isn't pretty. It isn't curated. It's yours, all the way through, for the first time in a while." #title "The Honest Wreckage")
			(if(MarkCaseFile(19))
				Print("Case Files: The Honest Wreckage, filed." #title "New Case File")
			)
		)
		(case 4
			Print("You let people see the parts you used to manage. A few flinched. You didn't take it back." #title "Seen and Not Sorry")
			(if(MarkCaseFile(20))
				Print("Case Files: Seen and Not Sorry, filed." #title "New Case File")
			)
		)
		(case 5
			Print("Being yourself had a price today. You paid it and you're still standing in the same shoes." #title "The Costly Truth")
			(if(MarkCaseFile(21))
				Print("Case Files: The Costly Truth, filed." #title "New Case File")
			)
		)
		(case 6
			Print("Nothing about today was smooth. All of it was real, which turned out to matter more." #title "Unpolished")
			(if(MarkCaseFile(22))
				Print("Case Files: Unpolished, filed." #title "New Case File")
			)
		)
		(case 7
			Print("You stopped insulating yourself from being seen. It sparked a little. You're still conducting." #title "The Exposed Wire")
			(if(MarkCaseFile(23))
				Print("Case Files: The Exposed Wire, filed." #title "New Case File")
			)
		)
	)
)
/******************************************************************************/
(procedure public (PrintSurvivalEnding3)
	(var variantIndex)
	= variantIndex Random(0 7)
	(switch(variantIndex)
		(case 0
			Print("You stopped filtering. Everything's a little too loud and a little too close to the surface right now." #title "Raw Nerve")
			(if(MarkCaseFile(24))
				Print("Case Files: Raw Nerve, filed." #title "New Case File")
			)
		)
		(case 1
			Print("The mask came off somewhere along the way and you never found a good moment to put it back on." #title "Nothing Between You And It")
			(if(MarkCaseFile(25))
				Print("Case Files: Nothing Between You And It, filed." #title "New Case File")
			)
		)
		(case 2
			Print("Whatever usually buffers you from the world just wasn't there today. You felt everything at full volume." #title "Exposed Wiring")
			(if(MarkCaseFile(26))
				Print("Case Files: Exposed Wiring, filed." #title "New Case File")
			)
		)
		(case 3
			Print("People got the real reaction, in real time, with none of the usual smoothing. It was a lot. For everyone." #title "The Unfiltered Version")
			(if(MarkCaseFile(27))
				Print("Case Files: The Unfiltered Version, filed." #title "New Case File")
			)
		)
		(case 4
			Print("You spent the day one comment away from visibly reacting to everything. Some days are just like that." #title "Too Close To The Surface")
			(if(MarkCaseFile(28))
				Print("Case Files: Too Close To The Surface, filed." #title "New Case File")
			)
		)
		(case 5
			Print("The usual layer between you and the day just wasn't there. You made it through anyway, a little rawer for it." #title "Skinless")
			(if(MarkCaseFile(29))
				Print("Case Files: Skinless, filed." #title "New Case File")
			)
		)
		(case 6
			Print("You didn't cover anything up today. It wasn't strategic. It just happened, and here you still are." #title "The Open Wound Approach")
			(if(MarkCaseFile(30))
				Print("Case Files: The Open Wound Approach, filed." #title "New Case File")
			)
		)
		(case 7
			Print("There was no version of today where you could smooth this over. So you didn't. That's new, for you." #title "Nowhere to Hide It")
			(if(MarkCaseFile(31))
				Print("Case Files: Nowhere to Hide It, filed." #title "New Case File")
			)
		)
	)
)
/******************************************************************************/
(procedure public (PrintSurvivalEnding4)
	(var variantIndex)
	= variantIndex Random(0 7)
	(switch(variantIndex)
		(case 0
			Print("You looked fine all day. You have no real idea what was actually fueling that." #title "Coasting on Empty")
			(if(MarkCaseFile(32))
				Print("Case Files: Coasting on Empty, filed." #title "New Case File")
			)
		)
		(case 1
			Print("From the outside, a completely normal day. On the inside, mostly static." #title "Running on Fumes and Good Posture")
			(if(MarkCaseFile(33))
				Print("Case Files: Running on Fumes and Good Posture, filed." #title "New Case File")
			)
		)
		(case 2
			Print("You showed up, said the right things, looked put-together. Nothing underneath was doing the same." #title "Presentable")
			(if(MarkCaseFile(34))
				Print("Case Files: Presentable, filed." #title "New Case File")
			)
		)
		(case 3
			Print("Everything worked. Nothing felt like anything. Both of those are true at once." #title "The Functional Hollow")
			(if(MarkCaseFile(35))
				Print("Case Files: The Functional Hollow, filed." #title "New Case File")
			)
		)
		(case 4
			Print("You got through today on muscle memory and social competence. The rest of you clocked out hours ago." #title "Autopilot, Well-Dressed")
			(if(MarkCaseFile(36))
				Print("Case Files: Autopilot, Well-Dressed, filed." #title "New Case File")
			)
		)
		(case 5
			Print("You were pleasant to everyone today. You couldn't say which of your own feelings, if any, showed up." #title "Numb But Nice About It")
			(if(MarkCaseFile(37))
				Print("Case Files: Numb But Nice About It, filed." #title "New Case File")
			)
		)
		(case 6
			Print("Nothing cracked today. Nothing underneath the surface was really there to crack, either." #title "The Smooth Surface")
			(if(MarkCaseFile(38))
				Print("Case Files: The Smooth Surface, filed." #title "New Case File")
			)
		)
		(case 7
			Print("You kept the shape of a normal day. Whatever's supposed to fill that shape took the day off." #title "Holding the Shape")
			(if(MarkCaseFile(39))
				Print("Case Files: Holding the Shape, filed." #title "New Case File")
			)
		)
	)
)
/******************************************************************************/
